# 开发环境配置文件

debug: true

custom:
    debug: true

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/phone_number?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: root

    thymeleaf:
        cache: false
