# 开发环境配置文件
debug: true

custom:
    debug: true

spring:
    thymeleaf:
        cache: false

    datasource:
        druid:
            filters: stat,wall,log4j2

            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
                session-stat-enable: true
                session-stat-max-count: 1000

            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: admin
                login-password: 123456
                allow: 127.0.0.1
                deny:
